image: 172.16.1.99/kundb/x86_64/builder:centos7

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - source ${CI_PROJECT_DIR}/ci/ci_scripts/before_script.env

stages:
  - postcommit
  - gold
  - release

postcommit:
  stage: postcommit
  script:
    - ${CI_SRC}/postcommit.sh
  only:
    - master@OLTP/mysql
    - kundb-1.1@OLTP/mysql
    - kundb-1.2@OLTP/mysql
  tags:
    - k8s

gold:
  stage: gold
  script:
    - ${CI_SRC}/gold.sh
  only:
    - master@OLTP/mysql
    - kundb-1.1@OLTP/mysql
    - kundb-1.2@OLTP/mysql
  tags:
    - k8s

release:
  stage: release
  script:
    - ${CI_SRC}/release.sh
  only:
    - master@OLTP/mysql
    - kundb-1.1@OLTP/mysql
    - kundb-1.2@OLTP/mysql
  tags:
    - k8s
